AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 15
